#define MAX_LINE_LENGTH 150
#define MAX_WORD_LENGTH 150
#define MAX_WORDS_PER_LINE 30
#define MAX_IDENTIFIERS 50

#define MAX_MESSAGE_STRING_LENGTH 150
#define MAX_LABEL_LENGTH 150
#define MAX_CONF_KEYS_PER_BLOCK 150

#include <stdint.h>
