//
// DO NOT MODIFY THIS FILE
//
// THIS FILE IS AUTOMATICALLY GENERATED IN ITS ENTIRETY
// ANY CHANGES MADE IN THIS FILE WILL BE OVERWRITTEN WITHOUT WARNING
// WHENEVER THE GLITCH IS INVOKED.
//

#include "itch_strings.h"

#include "out.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

uint16_t CallFunction(uint8_t func_xlat, ParamUnion params[]) {
	switch (func_xlat) {
		case 0:
			ShowBlocks();
			break;
		case 1:
			ShowSystem();
			break;
		case 2:
			ShowBlockByLabel(params[0].param_char_star);
			break;
		case 3:
			ShowBlockByID(params[0].param_int16_t);
			break;
		case 4:
			SendCommandToBlockLabel(params[0].param_char_star, params[1].param_uint16_t);
			break;
		case 5:
			SendCommandToBlockID(params[0].param_int16_t, params[1].param_uint16_t);
			break;
		case 6:
			ShowTime();
			break;
		case 7:
			SetTime(params[0].param_char_star);
			break;
		case 8:
			ShowDate();
			break;
		case 9:
			SetDate(params[0].param_char_star);
			break;
		case 10:
			ConfigClear();
			break;
		case 11:
			ConfigLoad();
			break;
		case 12:
			ConfigSave();
			break;
		case 13:
			ConfigBlockSystem(params[0].param_char_star, params[1].param_uint16_t, params[2].param_char_star);
			break;
		case 14:
			ConfigBlockInput(params[0].param_char_star, params[1].param_uint16_t, params[2].param_char_star);
			break;
		case 15:
			ConfigBlockMonitor(params[0].param_char_star, params[1].param_uint16_t, params[2].param_char_star);
			break;
		case 16:
			ConfigBlockSchedule(params[0].param_char_star, params[1].param_uint16_t, params[2].param_char_star);
			break;
		case 17:
			ConfigBlockRule(params[0].param_char_star, params[1].param_uint16_t, params[2].param_char_star);
			break;
		case 18:
			ConfigBlockController(params[0].param_char_star, params[1].param_uint16_t, params[2].param_char_star);
			break;
		case 19:
			ConfigBlockOutput(params[0].param_char_star, params[1].param_uint16_t, params[2].param_char_star);
			break;
		case 20:
			InitSetupAll();
			break;
		case 23:
			InitSetupBID(params[0].param_int16_t);
			break;
		case 21:
			InitValidateAll();
			break;
		case 24:
			InitValidateBID(params[0].param_int16_t);
			break;
		case 22:
			InitDisableAll();
			break;
		case 25:
			InitDisableBID(params[0].param_int16_t);
			break;
		case 26:
			AdminDisableBID(params[0].param_int16_t);
			break;
		case 27:
			AdminEnableBID(params[0].param_int16_t);
			break;
		case 28:
			AdminDeleteBID(params[0].param_int16_t);
			break;
		case 29:
			AdminCmdOnBID(params[0].param_int16_t);
			break;
		case 30:
			AdminCmdOffBID(params[0].param_int16_t);
			break;
		case 31:
			SystemReboot();
			break;
		default:
			return PE_FUNC_XLAT_NOT_MATCHED_IN_CALLFUNCTION;
			break;
	}
	return PEME_NO_ERROR;
}

uint16_t LookupIdentMap (char* key) {
	XLATMap temp;
	uint16_t idx = 0;
	while (idx < XLAT_IDENT_MAP_COUNT) {
		#ifdef ARDUINO
			memcpy_P(&temp, &ident_map[idx], sizeof(XLATMap));
		#else
			memcpy(&temp, &ident_map[idx], sizeof(XLATMap));
		#endif
		if(strcasecmp(temp.label, key) == 0) {
			return temp.xlat_id;
		}
		idx++;
	}
	return -1;
}

uint16_t LookupLookupMap (char* key) {
	XLATMap temp;
	uint16_t idx = 0;
	while (idx < XLAT_LOOKUP_MAP_COUNT) {
		#ifdef ARDUINO
			memcpy_P(&temp, &lookup_map[idx], sizeof(XLATMap));
		#else
			memcpy(&temp, &lookup_map[idx], sizeof(XLATMap));
		#endif
		if(strcasecmp(temp.label, key) == 0) {
			return temp.xlat_id;
		}
		idx++;
	}
	return -1;
}

uint16_t LookupFuncMap (char* key) {
	XLATMap temp;
	uint16_t idx = 0;
	while (idx < XLAT_FUNC_MAP_COUNT) {
		#ifdef ARDUINO
			memcpy_P(&temp, &func_map[idx], sizeof(XLATMap));
		#else
			memcpy(&temp, &func_map[idx], sizeof(XLATMap));
		#endif
		if(strcasecmp(temp.label, key) == 0) {
			return temp.xlat_id;
		}
		idx++;
	}
	return -1;
}

uint16_t LookupIdentifierMembers(uint16_t ident_xlat, char* lookup_string) {
	SimpleStringArray temp;
	uint16_t idx = 0;
	switch(ident_xlat) {
		case 0: {
			while (idx < LAST_BLOCK_CAT) {
				#ifdef ARDUINO
					memcpy_P(&temp, &block_cat_names[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &block_cat_names[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 1: {
			while (idx < LAST_BLOCK_TYPE) {
				#ifdef ARDUINO
					memcpy_P(&temp, &block_type_strings[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &block_type_strings[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 2: {
			while (idx < LAST_COMMAND) {
				#ifdef ARDUINO
					memcpy_P(&temp, &command_strings[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &command_strings[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 3: {
			while (idx < LAST_UNIT) {
				#ifdef ARDUINO
					memcpy_P(&temp, &unit_strings[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &unit_strings[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 4: {
			while (idx < LAST_UNIT_ABBR) {
				#ifdef ARDUINO
					memcpy_P(&temp, &unit_abbr_strings[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &unit_abbr_strings[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 5: {
			while (idx < LAST_DAY) {
				#ifdef ARDUINO
					memcpy_P(&temp, &day_strings[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &day_strings[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 6: {
			while (idx < LAST_INTERFACE) {
				#ifdef ARDUINO
					memcpy_P(&temp, &interface_strings[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &interface_strings[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 7: {
			while (idx < LAST_STATUS) {
				#ifdef ARDUINO
					memcpy_P(&temp, &status_strings[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &status_strings[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 8: {
			while (idx < LAST_SYS_CONFIG) {
				#ifdef ARDUINO
					memcpy_P(&temp, &sys_config_keys[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &sys_config_keys[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 9: {
			while (idx < LAST_IN_CONFIG) {
				#ifdef ARDUINO
					memcpy_P(&temp, &in_config_keys[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &in_config_keys[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 10: {
			while (idx < LAST_MON_CONFIG) {
				#ifdef ARDUINO
					memcpy_P(&temp, &mon_config_keys[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &mon_config_keys[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 11: {
			while (idx < LAST_SCH_CONFIG) {
				#ifdef ARDUINO
					memcpy_P(&temp, &sch_config_keys[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &sch_config_keys[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 12: {
			while (idx < LAST_RL_CONFIG) {
				#ifdef ARDUINO
					memcpy_P(&temp, &rl_config_keys[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &rl_config_keys[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 13: {
			while (idx < LAST_CON_CONFIG) {
				#ifdef ARDUINO
					memcpy_P(&temp, &con_config_keys[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &con_config_keys[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		case 14: {
			while (idx < LAST_OUT_CONFIG) {
				#ifdef ARDUINO
					memcpy_P(&temp, &out_config_keys[idx], sizeof(SimpleStringArray));
				#else
					memcpy(&temp, &out_config_keys[idx], sizeof(SimpleStringArray));
				#endif
				if(strcasecmp(lookup_string, temp.text) == 0) {
					return idx;
				}
				idx++;
			}
		}
			break;
		default:
		return 0;
	}
	return 0;
}

uint8_t LookupLookupMembers(uint16_t ident_xlat, char* lookup_string) {
	switch(ident_xlat) {
		case 0:
			return LookupBlockLabel(lookup_string);
			break;
		default:
		return 0;
	}
	return 0;
}

